package com.shinjaehun.suksuk.domain.division.model

enum class CellName {
    None,
    DivisorTens,
    DivisorOnes,
    DividendHundreds,
    DividendTens,
    DividendOnes,
    QuotientTens,
    QuotientOnes,
    Multiply1Hundreds,
    Multiply1Tens,
    Multiply1Ones,
    Subtract1Hundreds,
    Subtract1Tens,
    Subtract1Ones,
    Borrowed10DividendTens,
    Borrowed10DividendOnes,
    Borrowed10Subtract1Ones,
    Multiply2Hundreds,
    Multiply2Tens,
    Multiply2Ones,
    Subtract2Tens,
    Subtract2Ones,
    BorrowDividendHundreds,
    BorrowDividendTens,
    BorrowSubtract1Hundreds,
    BorrowSubtract1Tens,
    CarryDivisorTens,
}
